###
POST {{localhost}}/api/v1/register/customer/
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "check@1234$##",
    "retype_password": "check@1234$#",
    "first_name": "John",
    "last_name": "Doe",
    "user_profile": {
        "other_name": "Johnny",
        "date_of_birth": "2000-01-01",
        "phone_number": "1234567890"
    }
}